[drive]
# Limit (in bytes) below which an email will be sent to all
# interested parties.
limit = 10_000_000_000 # GB
# Windows expects invocation paths to end with '\'
letter = "C:\\"

[mail]
sender = "Server watcher"
username = "your.email@mail.com"
password = "your password in plain-text"
recepient_list = [ "me@mail.com", "admin@server.com" ]
server = "smtp.gmail.com"
port = 587