[drive]
# Limit (in bytes) below which emails will be sent.
limit_bytes = 10_000_000_000 # GB

# Which path should be watched for space.
#
# NOTE: Windows expects invocation paths to end with '\'
path = "/"


[mail]
# Language of the email (this does not affect loggine).
lang = "bg"

# Basic authentication
username = "your.email@mail.com"
password = "your password in plain-text"

# Mail Server
server = "smtp.gmail.com"
port = 587

# Human-readable name of the email sernder.
sender = "Server watcher"
# Who should receive the email.
recepient_list = [ "me@mail.com", "admin@server.com" ]
